[tool.black]
line-length = 79
target-version = ['py37']
exclude = '.env|venv|types_derived.py|migrations'

[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
line_length = 79
multi_line_output = 3
skip_glob = [".env"]
use_parentheses = true
